### ISSUE TITLE
Cooperation to get anonymized user data as app developer

### ISSUE THREAD

**Issue by christianlupus** [kenda/nextcloud-openhab#27]
Hello,

I am an app developer (of the cookbook app) and I recently opened this [discussion on the forum](https://help.nextcloud.com/t/generic-domain-for-app-development/147153). The idea was to provide a central domain for all app developers as a starting point. One could create sub-domains for each app to be used for documentation and other, more app-specific tasks.

One such issue was my request to have the option to collect some statistics on the installed versions. This triggered a significant push-back by some users that fear that their data is leaked out. They fear that the valuable name of Nextcloud as independent and not collecting any personal data might be at stake.

I personally think this is not too critical as I would like to collect only anonymized data and any app can do so once installed. It is just a matter of willingness.

Long story short: I would like to get the opinion on this by some other devs that might have their own agenda and pain points. Maybe this could be useful for you as well.

I will post this in a few repos in order to trigger a bit of honest discussion about the pros and cons.
Christian

**Comment by kenda** [comment]
Hi Christian,

Thanks for getting in touch about this and raising awareness. I feel about this from two perspectives:

As app developer I would like to get some numbers about active installations for example, because these numbers are always interesting.
As Nextcloud user, I really appreciate the privacy focus and that there is no "Send analytics data" checkbox hidden somewhere deep in the settings. I see Nextcloud as a role model here to show other applications that it is not necessary to always collect arbitrary data about the users. 

For me, the insights that your solutions would bring, does not outbalance the loss of trust and privacy it would bring. And although you say that the data would be of course anonymized, the safest data is the one that was not collected.

I will follow the discussion in the forum, but I'm not really supporting the initiative as of today.

Cheers,
Marcus
